apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hotel-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: quay.io/ruben/reservations-service:latest
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: hotel-reservations
spec:
  broker: default
  filter:
    attributes:
      type: HotelReservationRequest
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: hotel-service
---
apiVersion: eventing.knative.dev/v1beta1
kind: Trigger
metadata:
  name: hotel-reservations-cancel
spec:
  broker: default
  filter:
    attributes:
      type: CancelHotelReservation
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: hotel-service